# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='pixiv-api',
    version='0.3.7',
    description='A library for the Pixiv API.',
    python_requires='==3.*,>=3.6.0',
    project_urls={"repository": "https://github.com/azuline/pixiv-api"},
    author='azuline',
    author_email='azuline@riseup.net',
    license='Apache-2.0',
    packages=['pixivapi'],
    package_dir={"": "."},
    package_data={},
    install_requires=['cloudscraper==1.*,>=1.2.48', 'requests==2.*,>=2.0.0'],
    extras_require={
        "dev": [
            "flake8==3.*,>=3.7.0",
            "isort==4.*,>=4.3.0",
            "sphinx==2.*,>=2.1.0",
            "sphinx-rtd-theme==0.*,>=0.4.3",
        ]
    },
)
